# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: <div style="text-align:center"><img src ="https://67.media.tumblr.com/d99bfbc8e7f0a9153053d40cc658af23/tumblr_oelm22gaj21tpp2lco1_250.gif"/></div>

email: 
description:  ❋ ❋ ❋ ❋ ❋ ❋ ❋ ❋ ❋
description2: ❋ ❋ ❋ ❋ ❋ ❋ ❋ ❋ ❋
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gma96.github.io/" # the base hostname & protocol for your site
twitter_username: 
github_username:  gma96

# Build settings
markdown: kramdown
